---
- name: jameica role
  tags:
  - jameica
  block:

  # install java
  - name: Install Java with apt
    become: true
    ansible.builtin.apt:
      state: present
      name: default-jre

  # install opt
  - ansible.builtin.import_tasks: install_opt.yml

  # desktop integration
  - name: Copy .desktop-file to /usr/share/applications/jameica.desktop
    become: true
    notify: update-desktop-database
    ansible.builtin.copy:
      src: "{{ jameica_desktop_src }}"
      dest: /usr/share/applications/jameica.desktop
      owner: root
      group: root
      mode: u=rw,g=r,o=r
